name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Install Dependencies
        run: |
          cd services/loyalty && npm install
          cd ../payment && npm install
          cd ../reservation && npm install

      - name: Run Tests
        run: |
          cd services/loyalty && npm run test
          cd ../payment && npm run test
          cd ../reservation && npm run test

      - name: Build images
        timeout-minutes: 3
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          docker compose build

      - name: Run containers
        timeout-minutes: 3
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          docker compose up -d
          echo "------------------------- gateway logs -------------------------"
          docker compose logs gateway
          echo "------------------------- loyalty logs -------------------------"
          docker compose logs loyalty
          echo "------------------------- payment logs -------------------------"
          docker compose logs payment
          echo "------------------------- reservation logs -------------------------"
          docker compose logs reservation
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v